package Main;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import java.util.concurrent.ThreadLocalRandom;

public class PresetMaps {

    public static Set<Integer> getAvailableWidths(){
        return presets.keySet();
    }

    public static Pipe[][] getPreset(int width){
        ArrayList<Pipe[][]> list = presets.get(width);                        //kaart teatud suurusega 3, 5, 7, 9 või 11

        int randomList = ThreadLocalRandom.current().nextInt(0, list.size()); //praeguseks ainult 3 variandi
        Pipe[][] result = list.get(randomList);
        for (Pipe[] pipeRow : result) {
            for (Pipe item : pipeRow) {                                       //käiakse läbi kõik elemendid 2D massivis
                if(item == null)
                    continue;

                int randomRotations = ThreadLocalRandom.current().nextInt(0, 4); //0, 1, 2 või 3 korda
                for(int i = 0; i < randomRotations; i++){
                    item.rotateClockwise();             //kõik torud roteeritakse päripäevaselt
                }
            }
        }
        return result;
    }

    //Torustiku loomine - kõik torude otsad on omavahel seotud
    private static HashMap<Integer, ArrayList<Pipe[][]>> presets = new HashMap<Integer, ArrayList<Pipe[][]>>(){{
        put(3, new ArrayList<Pipe[][]>(){{
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, null, null, new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
        }});
        put(5, new ArrayList<Pipe[][]>(){{
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(false, true, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, false, true, true), null, new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, false, true, false), null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), null, null},
                    {null, new Pipe(false, false, true, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
        }});
        put(7, new ArrayList<Pipe[][]>(){{
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, false, true, true), null, null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
        }});
        put(9, new ArrayList<Pipe[][]>(){{
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, false, true)}
            });
        }});
        put(11, new ArrayList<Pipe[][]>(){{
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
            add(new Pipe[][]{
                    {new Pipe(false, true, false, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), null},
                    {null, new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, false, true, true), new Pipe(true, false, true, false), null, new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(false, true, true, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, false, true, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, false, true, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(false, false, true, true), new Pipe(false, true, true, false), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(false, true, true, false), new Pipe(true, false, false, true), null},
                    {null, new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, false, true, false), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, false, true, false), new Pipe(true, false, true, false), null, null},
                    {null, new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(false, true, false, true), new Pipe(true, false, false, true), new Pipe(true, true, false, false), new Pipe(false, true, false, true), new Pipe(false, false, false, true)}
            });
        }});
    }};
}
